const projects = [
  {
    title: 'Encontre Já',
    description: 'Serviço de listagem de prestadores de serviço informais.',
    imageUrl: '../assets/projects/EncontreJa.gif',
    technologies: [
      { name: 'Nextjs', description: 'Uma biblioteca JavaScript para construir interfaces de usuário', icon: 'nextjs' },
      { name: 'React', description: 'Uma plataforma para construir aplicativos React Native', icon: 'reactjs' },
      { name: 'TypeScript', description: 'Uma linguagem que adiciona tipagem estática ao JavaScript', icon: 'typescript' },
      { name: 'Styled Components', description: 'Uma biblioteca para estilização de componentes em React', icon: 'styledcomponents' },
      { name: 'Java', description: 'Um ambiente de execução para JavaScript no lado do servidor', icon: 'java' },
      { name: 'Azure', description: 'Uma plataforma de nuvem da Microsoft para desenvolvimento e serviços', icon: 'azure' },
      { name: 'Docker', description: 'Uma plataforma para desenvolver, enviar e executar aplicativos em contêineres', icon: 'docker' },
      { name: 'Figma', description: 'Uma ferramenta de design colaborativo para interfaces e protótipos', icon: 'figma' },
      { name: 'Git', description: 'Um sistema de controle de versão distribuído para rastrear mudanças no código-fonte', icon: 'git' },
    ],
    url: 'https://useencontreja.com.br/',
    githubUrl: '#',
  },
  {
    title: 'UCash',
    description: 'Aplicativo inovador focado especificamente em conversão de crédito.',
    imageUrl: '../assets/projects/UCash.gif',
    technologies: [
      { name: 'React Native', description: 'Uma biblioteca JavaScript para construir interfaces de usuário', icon: 'reactjs' },
      { name: 'Expo', description: 'Uma plataforma para construir aplicativos React Native', icon: 'expo' },
      { name: 'TypeScript', description: 'Uma linguagem que adiciona tipagem estática ao JavaScript', icon: 'typescript' },
      { name: 'Styled Components', description: 'Uma biblioteca para estilização de componentes em React', icon: 'styledcomponents' },
      { name: 'Node.js', description: 'Um ambiente de execução para JavaScript no lado do servidor', icon: 'nodejs' },
      { name: 'Express', description: 'Um framework para construir aplicativos web e APIs com Node.js', icon: 'express' },
      { name: 'Azure', description: 'Uma plataforma de nuvem da Microsoft para desenvolvimento e serviços', icon: 'azure' },
      { name: 'Docker', description: 'Uma plataforma para desenvolver, enviar e executar aplicativos em contêineres', icon: 'docker' },
      { name: 'Figma', description: 'Uma ferramenta de design colaborativo para interfaces e protótipos', icon: 'figma' },
      { name: 'Git', description: 'Um sistema de controle de versão distribuído para rastrear mudanças no código-fonte', icon: 'git' },
    ],
    url: 'https://useucash.com.br/',
    githubUrl: '#',
  },
  {
    title: 'Landing Page - Clube 2 de Junho',
    description: 'Landing Page criada para alugar clube e quadra de beach tenis.',
    imageUrl: '../assets/projects/Clube2deJunho.gif',
    technologies: [
      { name: 'HTML', description: 'A linguagem de marcação usada para estruturar o conteúdo da web.', icon: 'html5' },
      { name: 'CSS', description: 'Uma linguagem de estilo usada para descrever a apresentação de documentos HTML.', icon: 'css3' },
      { name: 'JavaScript', description: 'Uma linguagem de programação usada para adicionar interatividade e funcionalidades à web.', icon: 'js' },
      { name: 'Node.js', description: "Um runtime JavaScript baseado no motor V8 do Chrome", icon: 'nodejs' },
      { name: 'Express', description: 'Um framework para construir aplicativos web e APIs com Node.js', icon: 'express' },
      { name: 'PostgreSQL', description: 'Um banco de dados relacional de código aberto', icon: 'postgresql' },
      { name: 'Azure', description: 'Uma plataforma de nuvem da Microsoft para desenvolvimento e serviços', icon: 'azure' },
      { name: 'Webhook', description: 'Uma técnica para permitir comunicação entre sistemas', icon: 'tRPC' },
      { name: 'EzPayBank', description: 'Um serviço para processamento de pagamentos', icon: 'payment' },
    ],
    url: 'https://higorxi.github.io/clube2dejunho-LP/',
    githubUrl: '#',
  },
  {
    title: 'E-paper',
    description: 'Desafio técnico de um serviço de administração de documentos.',
    imageUrl: '../assets/projects/e-paper.png',
    technologies: [
      { name: 'Nextjs', description: 'Uma biblioteca JavaScript para construir interfaces de usuário', icon: 'nextjs' },
      { name: 'React', description: 'Uma plataforma para construir aplicativos React Native', icon: 'reactjs' },
      { name: 'TypeScript', description: 'Uma linguagem que adiciona tipagem estática ao JavaScript', icon: 'typescript' },
      { name: 'Styled Components', description: 'Uma biblioteca para estilização de componentes em React', icon: 'styledcomponents' },
      { name: 'Supabase', description: 'Banco de dados de fácil integração', icon: 'supabase' },
    ],
    url: 'https://front-end-rlv.vercel.app/',
    githubUrl: 'https://github.com/higorxi/front-end/tree/main',
  },
  {
    title: 'Dashboard Ambev - Hackaton',
    description: 'Dashboard criada para visualização de dados de perca, lotes e SKU, tudo para maximização de produção da Ambev Anápolis',
    imageUrl: '../assets/projects/hackaton.png',
    technologies: [
      { name: 'Nextjs', description: 'Uma biblioteca JavaScript para construir interfaces de usuário', icon: 'nextjs' },
      { name: 'React', description: 'Uma plataforma para construir aplicativos React Native', icon: 'reactjs' },
      { name: 'TypeScript', description: 'Uma linguagem que adiciona tipagem estática ao JavaScript', icon: 'typescript' },
      { name: 'Styled Components', description: 'Uma biblioteca para estilização de componentes em React', icon: 'styledcomponents' },
      { name: 'Node.js', description: "Um runtime JavaScript baseado no motor V8 do Chrome", icon: 'nodejs' },
      { name: 'Express', description: 'Um framework para construir aplicativos web e APIs com Node.js', icon: 'express' },
      { name: 'PostgreSQL', description: 'Um banco de dados relacional de código aberto', icon: 'postgresql' },
      { name: 'Azure', description: 'Uma plataforma de nuvem da Microsoft para desenvolvimento e serviços', icon: 'azure' },
    ],
    url: 'https://dashboard-hackaton.vercel.app/',
    githubUrl: 'https://github.com/higorxi/dashboard-hackaton/tree/main',
  },
  {
    title: 'ToDo List',
    description: 'ToDo List criado para desafio técnico.',
    imageUrl: '../assets/projects/todolist.png',
    technologies: [
      { name: 'React', description: 'Uma plataforma para construir aplicativos React Native', icon: 'reactjs' },
      { name: 'TypeScript', description: 'Uma linguagem que adiciona tipagem estática ao JavaScript', icon: 'typescript' },
      { name: 'Styled Components', description: 'Uma biblioteca para estilização de componentes em React', icon: 'styledcomponents' }
    ],
    url: 'https://legaplan.vercel.app/',
    githubUrl: 'https://github.com/higorxi/legaplan/tree/main',
  },
  {
    title: 'Portal Consulta Brasil',
    description: 'Sistema de consulta e integração com a base de dados do Consulta Brasil.',
    imageUrl: '../assets/projects/ConsultaBrasil.gif',
    technologies: [
      { name: 'Node.js', description: "Um runtime JavaScript baseado no motor V8 do Chrome", icon: 'nodejs' },
      { name: 'Nest.js', description: 'Um framework web Node.js minimalista e flexível', icon: 'nestjs' },
      { name: 'PostgreSQL', description: 'Um banco de dados relacional de código aberto', icon: 'postgresql' },
      { name: 'Azure', description: 'Uma plataforma de nuvem da Microsoft para desenvolvimento e serviços', icon: 'azure' },
      { name: 'Webhook', description: 'Uma técnica para permitir comunicação entre sistemas', icon: 'tRPC' },
      { name: 'EzPayBank', description: 'Um serviço para processamento de pagamentos', icon: 'payment' },
    ],
    url: 'https://www.portalconsultabrasil.com/',
    githubUrl: '#',
  },
  {
    title: 'Cidade Alta API & WEB',
    description: 'API e interface web para o projeto Cidade Alta.',
    imageUrl: '../assets/projects/CidadeAlta.gif',
    technologies: [
      { name: 'React', description: 'Uma biblioteca de JavaScript para construir interfaces de usuário', icon: 'reactjs' },
      { name: 'TypeScript', description: 'Uma linguagem que adiciona tipagem estática ao JavaScript', icon: 'typescript' },
      { name: 'Nest.js', description: 'Um framework web Node.js minimalista e flexível', icon: 'nestjs' },
      { name: 'PostgreSQL', description: 'Um banco de dados relacional de código aberto', icon: 'postgresql' },
      { name: 'Azure', description: 'Uma plataforma de nuvem da Microsoft para desenvolvimento e serviços', icon: 'azure' },
    ],
    url: 'https://cidadealta.vercel.app/login',
    githubUrl: 'https://github.com/higorxi/CidadeAltaWEB',
  },
  {
    title: 'Aplicativo de parcelamento de compras',
    description: 'Aplicativo para parcelamento de compras com integração de pagamento.',
    imageUrl: '../assets/projects/Woovi.gif',
    isVertical: true,
    technologies: [
      { name: 'React Native', description: 'Uma biblioteca JavaScript para construir interfaces de usuário', icon: 'reactjs' },
      { name: 'Expo', description: 'Uma plataforma para construir aplicativos React Native', icon: 'expo' },
      { name: 'TypeScript', description: 'Uma linguagem que adiciona tipagem estática ao JavaScript', icon: 'typescript' },
    ],
    githubUrl: '#',
  },
  {
    title: "API's",
    description: 'Conjunto de APIs para integração e serviços diversos.',
    imageUrl: '../assets/projects/API.gif',
    technologies: [
      { name: 'Node.js', description: 'Um runtime JavaScript baseado no motor V8 do Chrome', icon: 'nodejs' },
      { name: 'Express', description: 'Um framework para construir aplicativos web e APIs com Node.js', icon: 'express' },
      { name: 'TypeScript', description: 'Uma linguagem que adiciona tipagem estática ao JavaScript', icon: 'typescript' },
    ],
    githubUrl: '#',
  },
  {
    title: "Extensão WhatsApp",
    description: 'Extensão para integração e automação com o WhatsApp.',
    imageUrl: '../assets/projects/ExtensaoZap.jpg',
    technologies: [
      { name: 'JavaScript', description: 'Uma linguagem de programação para desenvolvimento web', icon: 'javascript' },
      { name: 'Chrome', description: 'O navegador Google Chrome', icon: 'chrome' },
    ],
    githubUrl: '#',
  },
  {
    title: "Extensão LowRAM",
    description: 'Extensão para otimização de recursos no navegador.',
    imageUrl: '/placeholder.svg',
    technologies: [
      { name: 'JavaScript', description: 'Uma linguagem de programação para desenvolvimento web', icon: 'javascript' },
      { name: 'Chrome', description: 'O navegador Google Chrome', icon: 'chrome' },
    ],
    githubUrl: '#',
  },
  {
    title: "Aplicativo para localizar CEP",
    description: 'Aplicativo para pesquisa de CEP e localização de endereços.',
    imageUrl: '/placeholder.svg',
    technologies: [
      { name: 'Flutter', description: 'Um toolkit de UI para criar aplicativos nativos', icon: 'flutter' },
      { name: 'Firebase', description: 'Uma plataforma para desenvolvimento de aplicativos móveis e web', icon: 'firebase' },
    ],
    githubUrl: '#',
  },
];

export default projects;
